# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: randjs
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: aws-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: anika

provider:
  name: handler
  runtime: nodejs20.x
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com

functions:
  hello:
    handler: hello.handler
    events:
      - httpApi:
          path: /hello
          method: get
